"""empty message

Revision ID: 985bef755d7c
Revises: 
Create Date: 2024-03-13 17:18:43.243501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985bef755d7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
